name: Build & Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login

      - name: Build & push
        run: |
          docker build -t registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/taintfactory:${{ github.sha }} .
          docker push registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/taintfactory:${{ github.sha }}

      - name: Tag latest
        run: |
          docker tag registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/taintfactory:${{ github.sha }} \
                     registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/taintfactory:latest
          docker push registry.digitalocean.com/${{ secrets.DOCR_REGISTRY }}/taintfactory:latest
